services:
  wadialfront:
    image: wadialfront
    ports:
      - "5173:5173"
    networks:
      - Wadial-network

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_DATABASE: WadialSaBeuss
      MYSQL_ROOT_PASSWORD: laraveldbname
    ports:
      - "3307:3306"
    networks:
      - Wadial-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  wadial-backend:
    image: wadial-backend
    ports:
      - "8181:8181"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: WadialSaBeuss
      DB_USERNAME: root
      DB_PASSWORD: laraveldbname
    networks:
      - Wadial-network

networks:
  Wadial-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local